### ISSUE TITLE
Encountering error 0xc000007b.

### ISSUE THREAD

**Issue by JoseErnestoOnGithub** [Lucario443/Lua-To-EXE#2]

**Comment by ExtremePro11299** [comment]
You need ucrtbased.dll to get this error. Do you have ucrtbased.dll somewhere in your computer? I got the same error when I was trying to fix this [issue](https://github.com/Lucario443/Lua-To-EXE/issues/1).

**Comment by JoseErnestoOnGithub** [comment]
Apologies! I'll close this issue for now.

**Comment by ExtremePro11299** [comment]
Reopen this issue when my [pull request](https://github.com/Lucario443/Lua-To-EXE/pull/3) gets merged. It should fix the other issue and replace it with this one.
